BEGIN;

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GoogleId" text NULL,
    "PasswordHash" text NOT NULL,
    "Email" text NOT NULL,
    "DisplayName" text NOT NULL,
    "AvatarUrl" text NOT NULL,
    "Credits" integer NOT NULL,
    "Wins" integer NOT NULL,
    "Losses" integer NOT NULL,
    "BestStreak" integer NOT NULL,
    "CurrentStreak" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "CreditTransactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Amount" integer NOT NULL,
    "Type" text NOT NULL,
    "Description" text NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_CreditTransactions_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "GameRooms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "KingUserId" integer NULL,
    "ChallengerUserId" integer NULL,
    "Status" text NOT NULL,
    "HostIp" text NULL,
    "UdpPort" integer NOT NULL,
    "GameRom" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_GameRooms_Users_ChallengerUserId"
        FOREIGN KEY ("ChallengerUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_GameRooms_Users_KingUserId"
        FOREIGN KEY ("KingUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "MatchHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameRoomId" integer NOT NULL,
    "WinnerId" integer NOT NULL,
    "LoserId" integer NOT NULL,
    "PlayedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_MatchHistories_Users_LoserId"
        FOREIGN KEY ("LoserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MatchHistories_Users_WinnerId"
        FOREIGN KEY ("WinnerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "MatchSessions" (
    "Id" uuid PRIMARY KEY,
    "GameRoomId" integer NOT NULL,
    "KingUserId" integer NOT NULL,
    "ChallengerUserId" integer NOT NULL,
    "WinnerUserId" integer NULL,
    "LoserUserId" integer NULL,
    "Status" text NOT NULL,
    "GameRom" text NOT NULL,
    "ResultSource" text NOT NULL,
    "LaunchSource" text NOT NULL,
    "ClientInstanceId" text NOT NULL,
    "EvidencePayload" text NULL,
    "ResultReason" text NULL,
    "LastIdempotencyKey" text NULL,
    "EmulatorProcessId" integer NULL,
    "CreatedByUserId" integer NOT NULL,
    "ReportedByUserId" integer NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "StartedAtUtc" timestamp with time zone NULL,
    "EndedAtUtc" timestamp with time zone NULL,
    "ReportedAtUtc" timestamp with time zone NULL,
    CONSTRAINT "FK_MatchSessions_GameRooms_GameRoomId"
        FOREIGN KEY ("GameRoomId") REFERENCES "GameRooms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MatchSessions_Users_ChallengerUserId"
        FOREIGN KEY ("ChallengerUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MatchSessions_Users_CreatedByUserId"
        FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MatchSessions_Users_KingUserId"
        FOREIGN KEY ("KingUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MatchSessions_Users_LoserUserId"
        FOREIGN KEY ("LoserUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MatchSessions_Users_ReportedByUserId"
        FOREIGN KEY ("ReportedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MatchSessions_Users_WinnerUserId"
        FOREIGN KEY ("WinnerUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "QueueEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameRoomId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Position" integer NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_QueueEntries_GameRooms_GameRoomId"
        FOREIGN KEY ("GameRoomId") REFERENCES "GameRooms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_QueueEntries_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Spectators" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameRoomId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_Spectators_GameRooms_GameRoomId"
        FOREIGN KEY ("GameRoomId") REFERENCES "GameRooms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Spectators_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_GoogleId" ON "Users" ("GoogleId");

CREATE INDEX IF NOT EXISTS "IX_CreditTransactions_UserId" ON "CreditTransactions" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_GameRooms_ChallengerUserId" ON "GameRooms" ("ChallengerUserId");
CREATE INDEX IF NOT EXISTS "IX_GameRooms_KingUserId" ON "GameRooms" ("KingUserId");

CREATE INDEX IF NOT EXISTS "IX_MatchHistories_LoserId" ON "MatchHistories" ("LoserId");
CREATE INDEX IF NOT EXISTS "IX_MatchHistories_WinnerId" ON "MatchHistories" ("WinnerId");

CREATE INDEX IF NOT EXISTS "IX_MatchSessions_ChallengerUserId" ON "MatchSessions" ("ChallengerUserId");
CREATE INDEX IF NOT EXISTS "IX_MatchSessions_CreatedByUserId" ON "MatchSessions" ("CreatedByUserId");
CREATE INDEX IF NOT EXISTS "IX_MatchSessions_GameRoomId_Status" ON "MatchSessions" ("GameRoomId", "Status");
CREATE INDEX IF NOT EXISTS "IX_MatchSessions_KingUserId" ON "MatchSessions" ("KingUserId");
CREATE INDEX IF NOT EXISTS "IX_MatchSessions_LoserUserId" ON "MatchSessions" ("LoserUserId");
CREATE INDEX IF NOT EXISTS "IX_MatchSessions_ReportedByUserId" ON "MatchSessions" ("ReportedByUserId");
CREATE INDEX IF NOT EXISTS "IX_MatchSessions_WinnerUserId" ON "MatchSessions" ("WinnerUserId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_QueueEntries_GameRoomId_UserId" ON "QueueEntries" ("GameRoomId", "UserId");
CREATE INDEX IF NOT EXISTS "IX_QueueEntries_UserId" ON "QueueEntries" ("UserId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Spectators_GameRoomId_UserId" ON "Spectators" ("GameRoomId", "UserId");
CREATE INDEX IF NOT EXISTS "IX_Spectators_UserId" ON "Spectators" ("UserId");

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260324030126_InitialPostgres', '10.0.0'
WHERE NOT EXISTS (
    SELECT 1
    FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260324030126_InitialPostgres'
);

COMMIT;