// <auto-generated />
using System;
using KingOfTheColonyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KingOfTheColonyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KingOfTheColonyApi.Models.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.GameRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChallengerUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameRom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostIp")
                        .HasColumnType("text");

                    b.Property<int?>("KingUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UdpPort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerUserId");

                    b.HasIndex("KingUserId");

                    b.ToTable("GameRooms");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.MatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameRoomId")
                        .HasColumnType("integer");

                    b.Property<int>("LoserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WinnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoserId");

                    b.HasIndex("WinnerId");

                    b.ToTable("MatchHistories");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.MatchSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChallengerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientInstanceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmulatorProcessId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidencePayload")
                        .HasColumnType("text");

                    b.Property<string>("GameRom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GameRoomId")
                        .HasColumnType("integer");

                    b.Property<int>("KingUserId")
                        .HasColumnType("integer");

                    b.Property<string>("LastIdempotencyKey")
                        .HasColumnType("text");

                    b.Property<string>("LaunchSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LoserUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReportedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ResultReason")
                        .HasColumnType("text");

                    b.Property<string>("ResultSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WinnerUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("KingUserId");

                    b.HasIndex("LoserUserId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("WinnerUserId");

                    b.HasIndex("GameRoomId", "Status");

                    b.ToTable("MatchSessions");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.QueueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameRoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameRoomId", "UserId")
                        .IsUnique();

                    b.ToTable("QueueEntries");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.Spectator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameRoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameRoomId", "UserId")
                        .IsUnique();

                    b.ToTable("Spectators");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.CreditTransaction", b =>
                {
                    b.HasOne("KingOfTheColonyApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.GameRoom", b =>
                {
                    b.HasOne("KingOfTheColonyApi.Models.User", "ChallengerUser")
                        .WithMany()
                        .HasForeignKey("ChallengerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KingOfTheColonyApi.Models.User", "KingUser")
                        .WithMany()
                        .HasForeignKey("KingUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChallengerUser");

                    b.Navigation("KingUser");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.MatchHistory", b =>
                {
                    b.HasOne("KingOfTheColonyApi.Models.User", "Loser")
                        .WithMany()
                        .HasForeignKey("LoserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KingOfTheColonyApi.Models.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loser");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.MatchSession", b =>
                {
                    b.HasOne("KingOfTheColonyApi.Models.User", "ChallengerUser")
                        .WithMany()
                        .HasForeignKey("ChallengerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KingOfTheColonyApi.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KingOfTheColonyApi.Models.GameRoom", "GameRoom")
                        .WithMany("MatchSessions")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingOfTheColonyApi.Models.User", "KingUser")
                        .WithMany()
                        .HasForeignKey("KingUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KingOfTheColonyApi.Models.User", "LoserUser")
                        .WithMany()
                        .HasForeignKey("LoserUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KingOfTheColonyApi.Models.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KingOfTheColonyApi.Models.User", "WinnerUser")
                        .WithMany()
                        .HasForeignKey("WinnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChallengerUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("GameRoom");

                    b.Navigation("KingUser");

                    b.Navigation("LoserUser");

                    b.Navigation("ReportedByUser");

                    b.Navigation("WinnerUser");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.QueueEntry", b =>
                {
                    b.HasOne("KingOfTheColonyApi.Models.GameRoom", "GameRoom")
                        .WithMany("Queue")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingOfTheColonyApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.Spectator", b =>
                {
                    b.HasOne("KingOfTheColonyApi.Models.GameRoom", "GameRoom")
                        .WithMany("Spectators")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingOfTheColonyApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KingOfTheColonyApi.Models.GameRoom", b =>
                {
                    b.Navigation("MatchSessions");

                    b.Navigation("Queue");

                    b.Navigation("Spectators");
                });
#pragma warning restore 612, 618
        }
    }
}
